version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    
  chunker:
    build: ./chunker
    ports:
      - "5004:5004"
    env_file:
      - .env
    volumes:
      - ./local_pdf:/app/shared_pdfs
  embeddings:
    build: ./embeddings
    ports:
      - "5001:5001"
    env_file:
      - .env

  reranker:
    build: ./reranker
    ports:
      - "5003:5003"
    env_file:
      - .env

  retriever:
    build: ./retriever
    ports:
      - "5002:5002"
    env_file:
      - .env

  vector_db:
    build: ./vector_db
    ports:
      - "5005:5005"
    depends_on:
      - redis

  scraper:
    build: ./scraper
    ports:
      - "5006:5006"
    volumes:
      - ./local_output:/app/file_storage
    shm_size: 1gb
    env_file:
      - .env
  llm:
    build: ./llm
    ports:
      - "5009:5009"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ragdb
      MYSQL_USER: raguser
      MYSQL_PASSWORD: ragpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fdh
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data


volumes:
  mysql_data:
  pgvector_data:

networks:
  default:
    external:
      name: shared_network


